#
# Wordpress
#

kind: Service
apiVersion: v1
metadata:
  name: wordpress-nodeport
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: {{ .Values.wordpress.nodePort }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: {{ .Values.wordpress.image }}
        imagePullPolicy: "IfNotPresent"
        env:
        - name: WORDPRESS_DB_HOST
          value: "tidb-service.{{ .Values.namespace }}.svc.cluster.local:4000"
        - name: WORDPRESS_DB_USER
          value: "root"
        - name: WORDPRESS_DB_PASSWORD
          value: ""
        volumeMounts:
        - name: wordpress-data-vol
          mountPath: /var/www/html
        readinessProbe:
          httpGet:
            path: /license.txt
            port: 80
          initialDelaySeconds: 0
          timeoutSeconds: 20
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 1
      volumes:
      - name: wordpress-data-vol
        persistentVolumeClaim:
          claimName: nfs
